#web容器配置
server:
  context-path: /
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#启用调试模式
debug: true
#日志配置
logging:
  config: classpath:log4j2-dev.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
