#web容器配置
server:
  context-path: /
  port: 80
  index: ${random.int}
eureka:
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
#日志配置
logging:
  config: classpath:log4j2-prod.xml
spring:
  redis:
    cluster:
      nodes: 127.0.0.1:7000, 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
      pool:
        max-active: 10
        max-wait: 10000
        max-idle: 20
        min-idle: 5
      cache-expire: 1800
      timeout: 10000