#web容器配置
server:
  context-path: /
  port: 1111
  index: ${random.int}
  tomcat:
    uri-encoding: UTF-8
#启用调试模式
debug: true
eureka:
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: true
    #表示是否从Eureka Server获取注册信息，默认为true
    fetch-registry: true
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
#日志配置
logging:
  config: classpath:log4j2-dev.xml