#web容器配置
server:
  context-path: /
  port: 9080
  index: ${random.int}
#启用调试模式
debug: true
#日志配置
logging:
  config: classpath:log4j2-dev.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://superboot:superboot@localhost:1111/eureka/
spring:
  #配置消息中心
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  redis:
    cluster:
      nodes: 127.0.0.1:7000, 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
      pool:
        max-active: 10
        max-wait: 10000
        max-idle: 20
        min-idle: 5
      cache-expire: 1800
      timeout: 10000
#关闭安全认证
management:
  security:
    enabled: false