#定义环境引用的配置文件
spring:
  profiles:
    active: dev
  application:
    name: super-boot-config-center
  http:
    encoding:
      force: true
      charset: UTF-8
    multipart:
      enabled: true
      max-file-size: 1024MB
  #热加载配置
  devtools:
    remote:
      secret: thisismysecret
  #配置中心使用Git
  cloud:
      config:
        server:
          git:
            uri: https://github.com/7040210/SuperBoot/
            # git仓库地址下的相对地址，可以配置多个，用,分割。
            search-paths: client-config
            # git仓库的账号
            username:
            password:
eureka:
  instance:
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 10
    #无心跳多久后,该服务失效
    lease-expiration-duration-in-seconds: 30
    appname: 配置中心
