#web容器配置
server:
  context-path: /
  port: 80
  index: ${random.int}
  tomcat:
    uri-encoding: UTF-8
#日志配置
logging:
  config: classpath:log4j2-prod.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  #配置消息中心
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
#关闭安全认证
management:
  security:
    enabled: false