#定义环境引用的配置文件
spring:
  application:
    name: super-boot-operation-center
  http:
    encoding:
      force: true
      charset: UTF-8
    multipart:
      enabled: true
      max-file-size: 1024MB
  #热加载配置
  devtools:
    remote:
      secret: thisismysecret
#日志配置
logging:
  config: classpath:log4j2-prod.xml
eureka:
  instance:
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 10
    #无心跳多久后,该服务失效
    lease-expiration-duration-in-seconds: 30
    appname: 监控中心
    instance-id: ${spring.application.name}:${random.int}
turbine:
  cluster-name-expression: default
  combine-host-port: true
  app-config: super-boot-secruity-center,super-boot-user-center,super-boot-gateway-center